version: '3.8'

services:
  flux-service:
    build:
      context: ./flux
      dockerfile: Dockerfile
    ports:
      - "${SD_ROUTE_PORT:-25001}:${SD_ROUTE_PORT:-25001}"
    volumes:
      - ./flux/images:/app/images
      - ./flux/instance:/app/instance  # 添加 flux 数据库目录映射
    env_file:
      - .env
    networks:
      - app-network

  oauth-service:
    build:
      context: ./oauth
      dockerfile: Dockerfile
    ports:
      - "${AUTH_SERVICE_PORT:-25002}:${AUTH_SERVICE_PORT:-25002}"
    volumes:
      - ./oauth/instance:/app/instance  # 添加 oauth 数据库目录映射
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  images-data:
